#!/bin/sh

ZIG_TRIPLE=$1
ZIG_OPTIMIZE=$2
echo "ZIG_TRIPLE=$ZIG_TRIPLE ZIG_OPTIMIZE=$ZIG_OPTIMIZE"

shift 2
echo "args to run: $@"

apk add musl-dev

echo "hi from build $PWD"

mkdir -p /zig-out/foo
echo "foobar" > /zig-out/foo/bar
echo "hello there" > /zig-out/hi
